

   CREATE SEQUENCE  "CAMEROUNID"."SEQ_ABISRECORDS_ID"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 359 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BIOMETRICS_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CAMEROUNID"."SEQ_BIOMETRICS_ID"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 87 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CITIZEN_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CAMEROUNID"."SEQ_CITIZEN_ID"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 359 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PAYMENT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CAMEROUNID"."SEQ_PAYMENT_ID"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PHOTOGRAPHY_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CAMEROUNID"."SEQ_PHOTOGRAPHY_ID"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 359 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REQUEST_ID
--------------------------------------------------------

   CREATE SEQUENCE  "CAMEROUNID"."SEQ_REQUEST_ID"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 359 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ABISRECORDS
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."ABISRECORDS" 
   (	"ID" NUMBER, 
	"IDCITIZEN" NUMBER, 
	"BIOMETRICTYPEID" NUMBER(*,0), 
	"ABISNUMBER" NUMBER(*,0), 
	"ABISTYPE" VARCHAR2(50 CHAR), 
	"APPLICANTIDENTITYNUMBER" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Table BIOMETRICS
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."BIOMETRICS" 
   (	"ID" NUMBER(*,0), 
	"APPLICANTIDENTITYNUMBER" VARCHAR2(50 CHAR), 
	"BIOMETRICTYPEID" NUMBER(*,0), 
	"IMAGEFORMATID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 CHAR), 
	"STATUS" VARCHAR2(50 CHAR), 
	"BIOMETRICSUBTYPEID" NUMBER(*,0) DEFAULT 0, 
	"USERID" VARCHAR2(50 CHAR), 
	"DATA" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" 
 LOB ("DATA") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CAMEROONIANREASON
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."CAMEROONIANREASON" 
   (	"CAMEROONIONREASONCODE" VARCHAR2(2 CHAR), 
	"CAMEROONIONREASONNAME_FR" VARCHAR2(255 CHAR), 
	"CAMEROONIONREASONNAME_EN" VARCHAR2(255 CHAR), 
	"DEPRECATED" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;

   COMMENT ON COLUMN "CAMEROUNID"."CAMEROONIANREASON"."DEPRECATED" IS '0 if the current record is used';
--------------------------------------------------------
--  DDL for Table CITIZEN
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."CITIZEN" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(68 CHAR), 
	"GIVENNAME" VARCHAR2(68 CHAR), 
	"NICKNAME" VARCHAR2(60 CHAR), 
	"BIRTHDATE_TECH" DATE, 
	"BIRTHDATE" VARCHAR2(10 CHAR), 
	"IDBIRTHCOUNTRY" VARCHAR2(3 CHAR), 
	"IDBIRTHDEPT" VARCHAR2(2 CHAR), 
	"IDBIRTHPLACE" VARCHAR2(5 CHAR), 
	"BIRTHPLACEOTHER" VARCHAR2(20 CHAR), 
	"IDBIRTHADDRESS" VARCHAR2(30 CHAR), 
	"IDRESIDENCECOUNTRY" VARCHAR2(3 CHAR), 
	"IDRESIDENCEDEPT" VARCHAR2(2 CHAR), 
	"IDRESIDENCEPLACE" VARCHAR2(5 CHAR), 
	"RESIDENCEPLACEOTHER" VARCHAR2(28 CHAR), 
	"RESIDENCEADDRESS" VARCHAR2(30 CHAR), 
	"IDFAMILYORIGINCOUNTRY" VARCHAR2(3 CHAR), 
	"IDFAMILYORIGINDEPT" VARCHAR2(2 CHAR), 
	"IDFAMILYORIGINPLACE" VARCHAR2(5 CHAR), 
	"FAMILYORIGINPLACEOTHER" VARCHAR2(28 CHAR), 
	"FAMILYORIGINADDRESS" VARCHAR2(24 CHAR), 
	"GENDER" VARCHAR2(1 CHAR), 
	"IDNATIONALITY" VARCHAR2(3 CHAR), 
	"IDOCCUPATION" VARCHAR2(3 CHAR), 
	"OCCUPATIONOTHER" VARCHAR2(100 CHAR), 
	"EMPLOYERSNAME" VARCHAR2(100 CHAR), 
	"EMPLOYERSPOBOX" VARCHAR2(20 CHAR), 
	"PHONENUMBER" VARCHAR2(15 CHAR), 
	"FATHERNAME" VARCHAR2(96 CHAR), 
	"FATHERBIRTHDATE" VARCHAR2(10 CHAR), 
	"FATHERBIRTHDATE_TECH" DATE, 
	"MOTHERNAME" VARCHAR2(96 CHAR), 
	"MOTHERBIRTHDATE" VARCHAR2(10 CHAR), 
	"MOTHERBIRTHDATE_TECH" DATE, 
	"IDCAMEROONIANREASON" VARCHAR2(2 CHAR), 
	"ENTRYDATE" DATE, 
	"HEIGHT" NUMBER(*,0), 
	"IDSKINCOLOR" VARCHAR2(2 CHAR), 
	"IDETHNICGROUP" VARCHAR2(3 CHAR), 
	"IDSPECIALMARK01" VARCHAR2(2 CHAR), 
	"IDSPECIALMARK02" VARCHAR2(2 CHAR), 
	"IDSPECIALMARK03" VARCHAR2(2 CHAR), 
	"IDSPECIALMARK04" VARCHAR2(2 CHAR), 
	"IDREQUEST" NUMBER, 
	"CREATIONDATE" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFICATIONDATE" TIMESTAMP (6), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"POLICENUMBER" VARCHAR2(17 CHAR), 
	"POLICEMANRANK" VARCHAR2(2 CHAR), 
	"IDEXCHANGETOOLKIT" NUMBER, 
	"ABISNUMBER" NUMBER(*,0), 
	"DYNAMICDATA" BLOB, 
	"ABISDUPLICATE" NUMBER(*,0), 
	"ABISPERSONKEEPID" VARCHAR2(50 CHAR), 
	"ABISKEEPDECISION" NUMBER(*,0), 
	"REGISTRATIONNUMBER" VARCHAR2(50 CHAR), 
	"ENROLMENTOPERATOR" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" 
 LOB ("DYNAMICDATA") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "CAMEROUNID"."CITIZEN"."GENDER" IS 'M or F';
   COMMENT ON COLUMN "CAMEROUNID"."CITIZEN"."HEIGHT" IS 'height in centimeters';
   COMMENT ON COLUMN "CAMEROUNID"."CITIZEN"."CREATIONDATE" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."CITIZEN"."CREATOR" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."CITIZEN"."MODIFICATIONDATE" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."CITIZEN"."MODIFIER" IS 'audit column';
--------------------------------------------------------
--  DDL for Table ETHNICGROUP
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."ETHNICGROUP" 
   (	"ETHNICGROUPCODE" VARCHAR2(3 CHAR), 
	"ETHNICGROUPNAME_FR" VARCHAR2(255 CHAR), 
	"ETHNICGROUPNAME_EN" VARCHAR2(255 CHAR), 
	"DEPRECATED" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;

   COMMENT ON COLUMN "CAMEROUNID"."ETHNICGROUP"."DEPRECATED" IS '0 if the current record is used';
--------------------------------------------------------
--  DDL for Table FINGERPRINTS
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."FINGERPRINTS" 
   (	"ID" NUMBER, 
	"IDCITIZEN" NUMBER, 
	"LEFTTHUMB" BLOB, 
	"REASONLEFTTHUMB" VARCHAR2(4 CHAR), 
	"LEFTINDEX" BLOB, 
	"REASONLEFTINDEX" VARCHAR2(3 CHAR), 
	"LEFTMIDDLE" BLOB, 
	"REASONLEFTMIDDLE" VARCHAR2(3 CHAR), 
	"LEFTRING" BLOB, 
	"REASONLEFTRING" VARCHAR2(3 CHAR), 
	"LEFTLITTLE" BLOB, 
	"REASONLEFTLITTLE" VARCHAR2(3 CHAR), 
	"RIGHTTHUMB" BLOB, 
	"REASONRIGHTTHUMB" VARCHAR2(3 CHAR), 
	"RIGHTINDEX" BLOB, 
	"REASONRIGHTINDE" VARCHAR2(3 CHAR), 
	"RIGHTMIDDLE" BLOB, 
	"REASONRIGHTMIDDLE" VARCHAR2(3 CHAR), 
	"RIGHTRING" BLOB, 
	"REASONRIGHTRING" VARCHAR2(3 CHAR), 
	"RIGHTLITTLE" BLOB, 
	"REASONRIGHTLITTLE" VARCHAR2(3 CHAR), 
	"CREATIONDATE" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFICATIONDATE" TIMESTAMP (6), 
	"MODIFIER" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" 
 LOB ("LEFTTHUMB") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("LEFTINDEX") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("LEFTMIDDLE") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("LEFTRING") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("LEFTLITTLE") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RIGHTTHUMB") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RIGHTINDEX") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RIGHTMIDDLE") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RIGHTRING") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RIGHTLITTLE") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "CAMEROUNID"."FINGERPRINTS"."CREATIONDATE" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."FINGERPRINTS"."CREATOR" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."FINGERPRINTS"."MODIFICATIONDATE" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."FINGERPRINTS"."MODIFIER" IS 'audit column';
--------------------------------------------------------
--  DDL for Table FINGERPRINTSREASON
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."FINGERPRINTSREASON" 
   (	"FINGERPRINTREASONCODE" VARCHAR2(3 CHAR), 
	"FINGERPRINTREASONNAME_FR" VARCHAR2(255 CHAR), 
	"FINGERPRINTREASONNAME_EN" VARCHAR2(255 CHAR), 
	"DEPRECATED" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;

   COMMENT ON COLUMN "CAMEROUNID"."FINGERPRINTSREASON"."DEPRECATED" IS '0 if the current record is used';
--------------------------------------------------------
--  DDL for Table LOCALIZATION
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."LOCALIZATION" 
   (	"ID" NUMBER, 
	"LOCALIZATIONCODE" VARCHAR2(10 CHAR), 
	"LOCALIZATIONNAME_FR" VARCHAR2(255 CHAR), 
	"LOCALIZATIONNAME_EN" VARCHAR2(255 CHAR), 
	"LVL" NUMBER, 
	"IDPARENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Table NATIONALITY
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."NATIONALITY" 
   (	"NATIONALITYCODE" VARCHAR2(3 CHAR), 
	"NATIONALITYNAME_FR" VARCHAR2(255 CHAR), 
	"NATIONALITYNAME_EN" VARCHAR2(255 CHAR), 
	"COUNTRYNAME_FR" VARCHAR2(255 CHAR), 
	"COUNTRYNAME_EN" VARCHAR2(255 CHAR), 
	"DEPRECATED_NATIONALITY" VARCHAR2(1 CHAR), 
	"DEPRECATED_COUNTRY" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;

   COMMENT ON COLUMN "CAMEROUNID"."NATIONALITY"."DEPRECATED_NATIONALITY" IS '1 if the current nationality is used';
   COMMENT ON COLUMN "CAMEROUNID"."NATIONALITY"."DEPRECATED_COUNTRY" IS '1 if the current country is used';
--------------------------------------------------------
--  DDL for Table OCCUPATION
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."OCCUPATION" 
   (	"OCCUPATIONCODE" VARCHAR2(3 CHAR), 
	"OCCUPATIONNAME_FR" VARCHAR2(255 CHAR), 
	"OCCUPATIONNAME_EN" VARCHAR2(255 CHAR), 
	"DEPRECATED" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;

   COMMENT ON COLUMN "CAMEROUNID"."OCCUPATION"."DEPRECATED" IS '0 if the current record is used';
--------------------------------------------------------
--  DDL for Table PARAMKIT
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."PARAMKIT" 
   (	"CODE" VARCHAR2(20 CHAR), 
	"VALUE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Table PHOTOGRAPHY
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."PHOTOGRAPHY" 
   (	"ID" NUMBER, 
	"IDCITIZEN" NUMBER, 
	"PHOTOJPEG" BLOB, 
	"PHOTOJP2K" BLOB, 
	"CREATIONDATE" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFICATIONDATE" TIMESTAMP (6), 
	"MODIFIER" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" 
 LOB ("PHOTOJPEG") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PHOTOJP2K") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "CAMEROUNID"."PHOTOGRAPHY"."CREATIONDATE" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."PHOTOGRAPHY"."CREATOR" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."PHOTOGRAPHY"."MODIFICATIONDATE" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."PHOTOGRAPHY"."MODIFIER" IS 'audit column';
--------------------------------------------------------
--  DDL for Table POLICEMANRANK
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."POLICEMANRANK" 
   (	"POLICEMANRANKCODE" VARCHAR2(2 CHAR), 
	"POLICEMANRANKNAME_FR" VARCHAR2(255 CHAR), 
	"POLICEMANRANKNAME_EN" VARCHAR2(255 CHAR), 
	"DEPRECATED" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Table POSTEIDENTIFICATION
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."POSTEIDENTIFICATION" 
   (	"ID" NUMBER, 
	"PICODE" VARCHAR2(4 CHAR), 
	"COMMISSARIAT_FR" VARCHAR2(255 CHAR), 
	"COMMISSARIAT_EN" VARCHAR2(255 CHAR), 
	"LOCALISATION" VARCHAR2(5 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Table REQUEST
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."REQUEST" 
   (	"ID" NUMBER, 
	"ENROLMENTDATE" TIMESTAMP (6), 
	"REGISTRATIONNUMBER" VARCHAR2(50 CHAR), 
	"IDPI" VARCHAR2(4 CHAR), 
	"CARDTYPE" VARCHAR2(3 CHAR), 
	"REQUESTTYPE" VARCHAR2(2 CHAR), 
	"CATEGORY" VARCHAR2(5 CHAR), 
	"PREVIOUSREQUESTIDKIT" VARCHAR2(20 CHAR), 
	"PREVIOUSDOCUMENTNUMBER" VARCHAR2(17 CHAR), 
	"PREVIOUSIDENTITYID" VARCHAR2(17 CHAR), 
	"IDDEPOSITCENTER" VARCHAR2(3 CHAR), 
	"NUMBEROFMAILINCLOSURESLIP" VARCHAR2(10 CHAR), 
	"RECEIVEDAMOUNT" NUMBER, 
	"LEFTAMOUNT" NUMBER, 
	"COMMENTS" VARCHAR2(255 CHAR), 
	"CREATIONDATE" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFICATIONDATE" TIMESTAMP (6), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"REQUESTIDKIT" VARCHAR2(20 CHAR), 
	"SYNTHESIS_FILENAME" VARCHAR2(255 CHAR), 
	"PURGEDEXPORTEDFILES" NUMBER(*,0), 
	"PURGEDPDFFILES" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;

   COMMENT ON COLUMN "CAMEROUNID"."REQUEST"."ENROLMENTDATE" IS 'application date';
   COMMENT ON COLUMN "CAMEROUNID"."REQUEST"."CREATIONDATE" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."REQUEST"."CREATOR" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."REQUEST"."MODIFICATIONDATE" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."REQUEST"."MODIFIER" IS 'audit column';
--------------------------------------------------------
--  DDL for Table SIGNATURE
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."SIGNATURE" 
   (	"ID" NUMBER, 
	"IDCITIZEN" NUMBER, 
	"SIGNATURE" BLOB, 
	"CREATIONDATE" VARCHAR2(4 CHAR), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFICATIONDATE" TIMESTAMP (6), 
	"MODIFIER" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" 
 LOB ("SIGNATURE") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "CAMEROUNID"."SIGNATURE"."CREATIONDATE" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."SIGNATURE"."CREATOR" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."SIGNATURE"."MODIFICATIONDATE" IS 'audit column';
   COMMENT ON COLUMN "CAMEROUNID"."SIGNATURE"."MODIFIER" IS 'audit column';
--------------------------------------------------------
--  DDL for Table SKINCOLOR
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."SKINCOLOR" 
   (	"SKINCOLORCODE" VARCHAR2(2 CHAR), 
	"SKINCOLORNAME_FR" VARCHAR2(255 CHAR), 
	"SKINCOLORNAME_EN" VARCHAR2(255 CHAR), 
	"DEPRECATED" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;

   COMMENT ON COLUMN "CAMEROUNID"."SKINCOLOR"."DEPRECATED" IS '0 if the current record is used';
--------------------------------------------------------
--  DDL for Table SPECIALMARK
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."SPECIALMARK" 
   (	"SPECIALMARKCODE" VARCHAR2(2 CHAR), 
	"SPECIALMARKNAME_FR" VARCHAR2(255 CHAR), 
	"SPECIALMARKNAME_EN" VARCHAR2(255 CHAR), 
	"DEPRECATED" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;

   COMMENT ON COLUMN "CAMEROUNID"."SPECIALMARK"."DEPRECATED" IS '0 if the current record is used';
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "CAMEROUNID"."USERS" 
   (	"ID" VARCHAR2(50 CHAR), 
	"USERNAME" VARCHAR2(50 CHAR), 
	"EMPLOYEEID" VARCHAR2(50 CHAR), 
	"NAME" VARCHAR2(60 BYTE), 
	"FIRSTNAME" VARCHAR2(120 BYTE), 
	"NICKNAME" VARCHAR2(120 BYTE), 
	"SEX" NUMBER(*,0), 
	"OCCUPATION" VARCHAR2(50 CHAR), 
	"LANDLINEPHONE" VARCHAR2(15 CHAR), 
	"MOBILEPHONE" VARCHAR2(15 CHAR), 
	"EMAIL" VARCHAR2(150 CHAR), 
	"RESIDENCE_COUNTRY" VARCHAR2(3 CHAR), 
	"RESIDENCE_COUNTY" VARCHAR2(2 CHAR), 
	"RESIDENCE_PLACE" VARCHAR2(5 CHAR), 
	"RESIDENCE_ADDRESS" VARCHAR2(30 CHAR), 
	"REGISTRATIONKITID" VARCHAR2(50 CHAR), 
	"ABISNUMBER" NUMBER(*,0), 
	"DYNAMICDATA" BLOB, 
	"ABISDUPLICATE" NUMBER(*,0), 
	"ABISPERSONKEEPID" VARCHAR2(50 CHAR), 
	"ABISKEEPDECISION" NUMBER(*,0), 
	"CREATEDATE" DATE, 
	"EXPORTDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" 
 LOB ("DYNAMICDATA") STORE AS BASICFILE (
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PK_LOCALIZATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_LOCALIZATION" ON "CAMEROUNID"."LOCALIZATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_ETHNICGROUP
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_ETHNICGROUP" ON "CAMEROUNID"."ETHNICGROUP" ("ETHNICGROUPCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_PARAMKIT
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_PARAMKIT" ON "CAMEROUNID"."PARAMKIT" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_NATIONALITY
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_NATIONALITY" ON "CAMEROUNID"."NATIONALITY" ("NATIONALITYCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_FINGERPRINTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_FINGERPRINTS" ON "CAMEROUNID"."FINGERPRINTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_CITIZEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_CITIZEN" ON "CAMEROUNID"."CITIZEN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_ABISRECORDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_ABISRECORDS" ON "CAMEROUNID"."ABISRECORDS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_SKINCOLOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_SKINCOLOR" ON "CAMEROUNID"."SKINCOLOR" ("SKINCOLORCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_BIOMETRICS
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_BIOMETRICS" ON "CAMEROUNID"."BIOMETRICS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_CAMEROONIANREASON
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_CAMEROONIANREASON" ON "CAMEROUNID"."CAMEROONIANREASON" ("CAMEROONIONREASONCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_FINGERPRINTSREASON
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_FINGERPRINTSREASON" ON "CAMEROUNID"."FINGERPRINTSREASON" ("FINGERPRINTREASONCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_POLICEMANRANK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_POLICEMANRANK" ON "CAMEROUNID"."POLICEMANRANK" ("POLICEMANRANKCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_USERS" ON "CAMEROUNID"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_PHOTOGRAPHY
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_PHOTOGRAPHY" ON "CAMEROUNID"."PHOTOGRAPHY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_OCCUPATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_OCCUPATION" ON "CAMEROUNID"."OCCUPATION" ("OCCUPATIONCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_SIGNATURE
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_SIGNATURE" ON "CAMEROUNID"."SIGNATURE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_SPECIALMARK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_SPECIALMARK" ON "CAMEROUNID"."SPECIALMARK" ("SPECIALMARKCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_POSTEIDENTIFICATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_POSTEIDENTIFICATION" ON "CAMEROUNID"."POSTEIDENTIFICATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  DDL for Index PK_REQUEST
--------------------------------------------------------

  CREATE UNIQUE INDEX "CAMEROUNID"."PK_REQUEST" ON "CAMEROUNID"."REQUEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT" ;
--------------------------------------------------------
--  Constraints for Table FINGERPRINTS
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."FINGERPRINTS" ADD CONSTRAINT "PK_FINGERPRINTS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ABISRECORDS
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."ABISRECORDS" ADD CONSTRAINT "PK_ABISRECORDS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POLICEMANRANK
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."POLICEMANRANK" ADD CONSTRAINT "PK_POLICEMANRANK" PRIMARY KEY ("POLICEMANRANKCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
  ALTER TABLE "CAMEROUNID"."POLICEMANRANK" MODIFY ("POLICEMANRANKCODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CITIZEN
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."CITIZEN" ADD CONSTRAINT "PK_CITIZEN" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
  ALTER TABLE "CAMEROUNID"."CITIZEN" MODIFY ("ENROLMENTOPERATOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSTEIDENTIFICATION
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."POSTEIDENTIFICATION" ADD CONSTRAINT "PK_POSTEIDENTIFICATION" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHOTOGRAPHY
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."PHOTOGRAPHY" ADD CONSTRAINT "PK_PHOTOGRAPHY" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ETHNICGROUP
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."ETHNICGROUP" ADD CONSTRAINT "PK_ETHNICGROUP" PRIMARY KEY ("ETHNICGROUPCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FINGERPRINTSREASON
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."FINGERPRINTSREASON" ADD CONSTRAINT "PK_FINGERPRINTSREASON" PRIMARY KEY ("FINGERPRINTREASONCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SIGNATURE
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."SIGNATURE" ADD CONSTRAINT "PK_SIGNATURE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CAMEROONIANREASON
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."CAMEROONIANREASON" ADD CONSTRAINT "PK_CAMEROONIANREASON" PRIMARY KEY ("CAMEROONIONREASONCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BIOMETRICS
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."BIOMETRICS" ADD CONSTRAINT "PK_BIOMETRICS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
  ALTER TABLE "CAMEROUNID"."BIOMETRICS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CAMEROUNID"."BIOMETRICS" MODIFY ("IMAGEFORMATID" NOT NULL ENABLE);
  ALTER TABLE "CAMEROUNID"."BIOMETRICS" MODIFY ("BIOMETRICTYPEID" NOT NULL ENABLE);
  ALTER TABLE "CAMEROUNID"."BIOMETRICS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
  ALTER TABLE "CAMEROUNID"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CAMEROUNID"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "CAMEROUNID"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OCCUPATION
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."OCCUPATION" ADD CONSTRAINT "PK_OCCUPATION" PRIMARY KEY ("OCCUPATIONCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPECIALMARK
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."SPECIALMARK" ADD CONSTRAINT "PK_SPECIALMARK" PRIMARY KEY ("SPECIALMARKCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NATIONALITY
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."NATIONALITY" ADD CONSTRAINT "PK_NATIONALITY" PRIMARY KEY ("NATIONALITYCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REQUEST
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."REQUEST" ADD CONSTRAINT "PK_REQUEST" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
  ALTER TABLE "CAMEROUNID"."REQUEST" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "CAMEROUNID"."REQUEST" MODIFY ("REQUESTTYPE" NOT NULL ENABLE);
  ALTER TABLE "CAMEROUNID"."REQUEST" MODIFY ("CARDTYPE" NOT NULL ENABLE);
  ALTER TABLE "CAMEROUNID"."REQUEST" MODIFY ("IDPI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SKINCOLOR
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."SKINCOLOR" ADD CONSTRAINT "PK_SKINCOLOR" PRIMARY KEY ("SKINCOLORCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARAMKIT
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."PARAMKIT" ADD CONSTRAINT "PK_PARAMKIT" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCALIZATION
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."LOCALIZATION" ADD CONSTRAINT "PK_LOCALIZATION" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_COESYS_CAMEROUNID_DAT"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ABISRECORDS
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."ABISRECORDS" ADD CONSTRAINT "FK_ABISRECORDS_CITIZEN" FOREIGN KEY ("IDCITIZEN")
	  REFERENCES "CAMEROUNID"."CITIZEN" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BIOMETRICS
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."BIOMETRICS" ADD CONSTRAINT "FK_BIOMETRICS_IDUSER" FOREIGN KEY ("USERID")
	  REFERENCES "CAMEROUNID"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CITIZEN
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."CITIZEN" ADD CONSTRAINT "FK_CITIZEN_IDREQUEST" FOREIGN KEY ("IDREQUEST")
	  REFERENCES "CAMEROUNID"."REQUEST" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FINGERPRINTS
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."FINGERPRINTS" ADD CONSTRAINT "FK_FINGERPRINTS_IDCITIZEN" FOREIGN KEY ("IDCITIZEN")
	  REFERENCES "CAMEROUNID"."CITIZEN" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHOTOGRAPHY
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."PHOTOGRAPHY" ADD CONSTRAINT "FK_PHOTOGRAPHY_IDCITIZEN" FOREIGN KEY ("IDCITIZEN")
	  REFERENCES "CAMEROUNID"."CITIZEN" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SIGNATURE
--------------------------------------------------------

  ALTER TABLE "CAMEROUNID"."SIGNATURE" ADD CONSTRAINT "FK_SIGNATURE_IDCITIZEN" FOREIGN KEY ("IDCITIZEN")
	  REFERENCES "CAMEROUNID"."CITIZEN" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ABISRECORDS_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CAMEROUNID"."TRG_ABISRECORDS_ID" 
  BEFORE INSERT ON ABISRECORDS
  FOR EACH ROW
DECLARE
BEGIN
  IF( :new.id IS NULL OR :new.id = 0)
  THEN
    :new.id := SEQ_ABISRECORDS_ID.nextval;
  END IF;
END;
/
ALTER TRIGGER "CAMEROUNID"."TRG_ABISRECORDS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BIOMETRICS_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CAMEROUNID"."TRG_BIOMETRICS_ID" 
  BEFORE INSERT ON Biometrics
  FOR EACH ROW
DECLARE
BEGIN
  IF( :new.id IS NULL OR :new.id = 0)
  THEN
    :new.id := SEQ_BIOMETRICS_ID.nextval;
  END IF;
END;
/
ALTER TRIGGER "CAMEROUNID"."TRG_BIOMETRICS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_CITIZEN_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CAMEROUNID"."TRG_CITIZEN_ID" 
  BEFORE INSERT ON CITIZEN
  FOR EACH ROW
DECLARE
BEGIN
  IF( :new.id IS NULL OR :new.id = 0)
  THEN
    :new.id := SEQ_CITIZEN_ID.nextval;
  END IF;
END;
/
ALTER TRIGGER "CAMEROUNID"."TRG_CITIZEN_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PHOTOGRAPHY_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CAMEROUNID"."TRG_PHOTOGRAPHY_ID" 
  BEFORE INSERT ON PHOTOGRAPHY
  FOR EACH ROW
DECLARE
BEGIN
  IF( :new.id IS NULL OR :new.id = 0)
  THEN
    :new.id := SEQ_PHOTOGRAPHY_ID.nextval;
  END IF;
END;
/
ALTER TRIGGER "CAMEROUNID"."TRG_PHOTOGRAPHY_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_REQUEST_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CAMEROUNID"."TRG_REQUEST_ID" 
  BEFORE INSERT ON REQUEST
  FOR EACH ROW
DECLARE
BEGIN
  IF( :new.id IS NULL OR :new.id = 0)
  THEN
    :new.id := SEQ_REQUEST_ID.nextval;
  END IF;
END;
/
ALTER TRIGGER "CAMEROUNID"."TRG_REQUEST_ID" ENABLE;
